### ISSUE TITLE
Accepting contributions?

### ISSUE THREAD

**Issue by justin-watkinson-sp** [ZipRecruiter/cloudwatching#1]
Hello there!

I wanted to say thanks for taking on this challenge.  I know it is a common one and I was looking for something along these lines, and was just about to write one myself.

By chance, are you accepting PRs to this project, or is the intent to let people use the library portions as-is?

Nothing concrete yet, but wanted to get a sense of the intent of this project going forward.

Thanks!

**Comment by frioux** [comment]
Definitely accepting PRs!  There's an unmerged branch with the comically named `br-1` that would support two of the things I expect the community to need (modification of metrics before surfacing them, renaming the metrics themselves, etc) but otherwise, as long as it doesn't break backcompat too much or is too niche of a feature, I think we're happy to accept stuff and work with you to get it merged.

**Comment by justin-watkinson-sp** [comment]
Thanks for the response!  That sounds great - a few ideas are brewing already, I'll make new issues for those.
